---
# Handlers for Role 01: VM Provisioning

- name: Restart sshd
  ansible.builtin.systemd:
    name: ssh
    state: restarted

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
